# Uncomment the next line to define a global platform for your project
 platform :ios, '11.2'

target 'Messenger' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Messenger
pod 'Firebase'
pod 'Firebase/Database'
pod 'ColorPickerSlider'

end
